import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedAncikainipacarnyaDilanMerekasalingmengenalsetelahDilans.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedRectangle183Widget8.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedGroup117Widget7.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedKode201Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedAncikaWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedDeskripsiWidget7.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedRectangle189Widget7.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedRectangle187Widget7.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedPenulisPidiBaiqWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedStok3Widget7.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget/generated/GeneratedRectangle185Widget7.dart';

/* Frame iPhone SE - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 568.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle183Widget8(),
              ),
              Positioned(
                left: 12.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle185Widget7(),
              ),
              Positioned(
                left: 35.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 400.0,
                child: GeneratedRectangle187Widget7(),
              ),
              Positioned(
                left: 115.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 130.0,
                child: GeneratedGroup117Widget7(),
              ),
              Positioned(
                left: 87.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 198.0,
                child: GeneratedRectangle189Widget7(),
              ),
              Positioned(
                left: 92.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 79.0,
                child:
                    GeneratedAncikainipacarnyaDilanMerekasalingmengenalsetelahDilans(),
              ),
              Positioned(
                left: 93.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 14.0,
                child: GeneratedKode201Widget(),
              ),
              Positioned(
                left: 119.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 14.0,
                child: GeneratedPenulisPidiBaiqWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 17.0,
                child: GeneratedDeskripsiWidget7(),
              ),
              Positioned(
                left: 93.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 14.0,
                child: GeneratedStok3Widget7(),
              ),
              Positioned(
                left: 138.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 22.0,
                child: GeneratedAncikaWidget(),
              )
            ]),
      ),
    ));
  }
}
