import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedDeskripsiWidget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedMajalahWanitaWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedRectangle187Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedRectangle189Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedRectangle185Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedKode101Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedGroup117Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedPenulisHitawasanaLuhurWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedStok3Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedRectangle183Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese14widget/generated/GeneratedPrestigeRaisaAndrianaWidget.dart';

/* Frame iPhone SE - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 568.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle183Widget6(),
              ),
              Positioned(
                left: 12.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle185Widget5(),
              ),
              Positioned(
                left: 35.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 400.0,
                child: GeneratedRectangle187Widget5(),
              ),
              Positioned(
                left: 115.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 130.0,
                child: GeneratedGroup117Widget5(),
              ),
              Positioned(
                left: 87.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 198.0,
                child: GeneratedRectangle189Widget5(),
              ),
              Positioned(
                left: 92.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 13.0,
                child: GeneratedMajalahWanitaWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 14.0,
                child: GeneratedKode101Widget4(),
              ),
              Positioned(
                left: 97.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 14.0,
                child: GeneratedPenulisHitawasanaLuhurWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 17.0,
                child: GeneratedDeskripsiWidget5(),
              ),
              Positioned(
                left: 93.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 14.0,
                child: GeneratedStok3Widget5(),
              ),
              Positioned(
                left: 82.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 19.0,
                child: GeneratedPrestigeRaisaAndrianaWidget(),
              )
            ]),
      ),
    ));
  }
}
