import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle11Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle17Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle13Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedLine3Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle10Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedGroup1Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedBukuWidget7.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle1Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedLine4Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedMajalahWidget7.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedTerbaruWidget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle14Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle12Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedLine6Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedLine5Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedRectangle16Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedLine1Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget1/generated/GeneratedLine2Widget2.dart';

/* Frame iPhone SE - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE4Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 706.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle1Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 35.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: 100.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 24.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 100.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 132.1968231201172,
                height: 1.0,
                child: GeneratedLine1Widget2(),
              ),
              Positioned(
                left: 230.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 132.1968231201172,
                height: 1.0,
                child: GeneratedLine2Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine3Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine4Widget2(),
              ),
              Positioned(
                left: 60.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 20.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 166.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 20.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 86.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 20.0,
                child: GeneratedMajalahWidget7(),
              ),
              Positioned(
                left: 198.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 20.0,
                child: GeneratedBukuWidget7(),
              ),
              Positioned(
                left: 10.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine5Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine6Widget2(),
              ),
              Positioned(
                left: 40.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 12.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 45.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 15.0,
                child: GeneratedTerbaruWidget6(),
              ),
              Positioned(
                left: 38.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle10Widget6(),
              ),
              Positioned(
                left: 38.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle12Widget6(),
              ),
              Positioned(
                left: 38.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle14Widget6(),
              ),
              Positioned(
                left: 38.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle16Widget6(),
              ),
              Positioned(
                left: 196.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle11Widget6(),
              ),
              Positioned(
                left: 196.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle13Widget6(),
              ),
              Positioned(
                left: 196.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle15Widget6(),
              ),
              Positioned(
                left: 196.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle17Widget6(),
              ),
              Positioned(
                left: 280.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup1Widget6(),
              )
            ]),
      ),
    ));
  }
}
