import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahkategoriwidget/generated/GeneratedRectangle50Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahkategoriwidget/generated/GeneratedRectangle52Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahkategoriwidget/generated/GeneratedMasukkankategoriWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahkategoriwidget/generated/GeneratedRectangle48Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahkategoriwidget/generated/GeneratedSimpanWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahkategoriwidget/generated/GeneratedHapusWidget11.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahkategoriwidget/generated/GeneratedRectangle53Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahkategoriwidget/generated/GeneratedGroup5Widget.dart';

/* Frame Admin tambah kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdmintambahkategoriWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 224, 224),
                ),
              ),
              Positioned(
                left: 293.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 693.0,
                height: 323.0,
                child: GeneratedRectangle48Widget3(),
              ),
              Positioned(
                left: 293.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 693.0,
                height: 115.35713958740234,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 293.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 693.0,
                height: 57.0,
                child: GeneratedRectangle50Widget1(),
              ),
              Positioned(
                left: 293.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 693.0,
                height: 46.0,
                child: GeneratedRectangle52Widget1(),
              ),
              Positioned(
                left: 293.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 693.0,
                height: 47.0,
                child: GeneratedRectangle53Widget1(),
              ),
              Positioned(
                left: 325.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 27.0,
                child: GeneratedMasukkankategoriWidget(),
              ),
              Positioned(
                left: 625.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 31.0,
                child: GeneratedSimpanWidget(),
              ),
              Positioned(
                left: 631.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 30.0,
                child: GeneratedHapusWidget11(),
              )
            ]),
      ),
    ));
  }
}
