import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle12Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedGroup1Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle17Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle16Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle14Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle11Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedBukuWidget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedTerbaruWidget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle15Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedMajalahWidget6.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle10Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle1Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle13Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese5widget/generated/GeneratedRectangle5Widget1.dart';

/* Frame iPhone SE - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 706.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle1Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 35.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 100.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 24.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 100.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 132.1968231201172,
                height: 1.0,
                child: GeneratedLine1Widget1(),
              ),
              Positioned(
                left: 230.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 132.1968231201172,
                height: 1.0,
                child: GeneratedLine2Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine3Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine4Widget1(),
              ),
              Positioned(
                left: 60.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 20.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 166.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 20.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 86.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 20.0,
                child: GeneratedMajalahWidget6(),
              ),
              Positioned(
                left: 198.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 20.0,
                child: GeneratedBukuWidget6(),
              ),
              Positioned(
                left: 10.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine5Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 12.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 45.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 15.0,
                child: GeneratedTerbaruWidget5(),
              ),
              Positioned(
                left: 38.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 110.0,
                child: GeneratedRectangle10Widget5(),
              ),
              Positioned(
                left: 38.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 110.0,
                child: GeneratedRectangle12Widget5(),
              ),
              Positioned(
                left: 38.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 110.0,
                child: GeneratedRectangle14Widget5(),
              ),
              Positioned(
                left: 38.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 110.0,
                child: GeneratedRectangle16Widget5(),
              ),
              Positioned(
                left: 196.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 110.0,
                child: GeneratedRectangle11Widget5(),
              ),
              Positioned(
                left: 196.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 110.0,
                child: GeneratedRectangle13Widget5(),
              ),
              Positioned(
                left: 196.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 110.0,
                child: GeneratedRectangle15Widget5(),
              ),
              Positioned(
                left: 196.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 110.0,
                child: GeneratedRectangle17Widget5(),
              ),
              Positioned(
                left: 280.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup1Widget5(),
              )
            ]),
      ),
    ));
  }
}
