import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedStok3Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedDeskripsiWidget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedKode101Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedRectangle183Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedHampirsetiapfakultasbahkanprogramstudimenerbitkanpedoma.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedRectangle189Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedPenulisDrAdibSofiaSSMHumWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedRectangle185Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedGroup117Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedRectangle187Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese12widget/generated/GeneratedMetodePenulisanKaryaIlmiahWidget.dart';

/* Frame iPhone SE - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 568.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle183Widget3(),
              ),
              Positioned(
                left: 12.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle185Widget2(),
              ),
              Positioned(
                left: 35.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 400.0,
                child: GeneratedRectangle187Widget2(),
              ),
              Positioned(
                left: 115.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 130.0,
                child: GeneratedGroup117Widget2(),
              ),
              Positioned(
                left: 87.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 198.0,
                child: GeneratedRectangle189Widget2(),
              ),
              Positioned(
                left: 92.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 90.0,
                child:
                    GeneratedHampirsetiapfakultasbahkanprogramstudimenerbitkanpedoma(),
              ),
              Positioned(
                left: 93.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 14.0,
                child: GeneratedKode101Widget1(),
              ),
              Positioned(
                left: 79.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 14.0,
                child: GeneratedPenulisDrAdibSofiaSSMHumWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 17.0,
                child: GeneratedDeskripsiWidget2(),
              ),
              Positioned(
                left: 93.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 14.0,
                child: GeneratedStok3Widget2(),
              ),
              Positioned(
                left: 59.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 19.0,
                child: GeneratedMetodePenulisanKaryaIlmiahWidget(),
              )
            ]),
      ),
    ));
  }
}
