import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedTambahkandeskripsiWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedTidakadafileyangdipilihWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedResetWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedRectangle53Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedMasukkankategoriWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedMasukkanjudulbukuWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedPilihFileWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedRectangle50Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedRectangle58Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedGroup5Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedSimpanWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedMasukkanpenulisWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedRectangle61Widget.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedRectangle48Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedRectangle56Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadmintambahbukuwidget/generated/GeneratedRectangle52Widget2.dart';

/* Frame Admin tambah buku
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdmintambahbukuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 224, 224),
                ),
              ),
              Positioned(
                left: 320.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 514.0,
                child: GeneratedRectangle48Widget4(),
              ),
              Positioned(
                left: 320.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 100.0,
                child: GeneratedGroup5Widget1(),
              ),
              Positioned(
                left: 320.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 50.0,
                child: GeneratedRectangle50Widget2(),
              ),
              Positioned(
                left: 320.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 50.0,
                child: GeneratedRectangle56Widget1(),
              ),
              Positioned(
                left: 320.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 50.0,
                child: GeneratedRectangle58Widget2(),
              ),
              Positioned(
                left: 320.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 50.0,
                child: GeneratedRectangle60Widget(),
              ),
              Positioned(
                left: 320.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 50.0,
                child: GeneratedRectangle61Widget(),
              ),
              Positioned(
                left: 320.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 40.0,
                child: GeneratedRectangle52Widget2(),
              ),
              Positioned(
                left: 320.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 640.0,
                height: 40.0,
                child: GeneratedRectangle53Widget2(),
              ),
              Positioned(
                left: 341.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 24.0,
                child: GeneratedMasukkanjudulbukuWidget(),
              ),
              Positioned(
                left: 341.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 24.0,
                child: GeneratedMasukkankategoriWidget1(),
              ),
              Positioned(
                left: 423.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 24.0,
                child: GeneratedTidakadafileyangdipilihWidget(),
              ),
              Positioned(
                left: 341.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 20.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 341.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 24.0,
                child: GeneratedMasukkanpenulisWidget(),
              ),
              Positioned(
                left: 341.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 24.0,
                child: GeneratedTambahkandeskripsiWidget(),
              ),
              Positioned(
                left: 627.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 27.0,
                child: GeneratedSimpanWidget1(),
              ),
              Positioned(
                left: 635.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 27.0,
                child: GeneratedResetWidget(),
              ),
              Positioned(
                left: 349.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 20.0,
                child: GeneratedPilihFileWidget(),
              )
            ]),
      ),
    ));
  }
}
