import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle46Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedEditWidget9.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedEditWidget11.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/Generated1Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedNoWidget6.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedEditBukuWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle43Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedKategoriWidget5.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedTambahkanBukuWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedEditKategoriWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedHapusWidget10.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedAltheaGrisheldaAltheaRajinWidget3.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedSearchWidget3.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedKomikWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/Generated3Widget6.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle21Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle42Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle45Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle44Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle35Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedEDITKATEGORIWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedEditWidget8.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedMajalahWidget10.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedEditWidget10.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle18Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle10Widget11.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedLogoutWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle23Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedHapusWidget8.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedNovelWidget17.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedTambahkanKategoriWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedGroup1Widget11.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle34Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedHapusWidget9.dart';
import 'package:flutterapp/bookspaceapp/generatedadminmanagekategoriwidget/generated/GeneratedRectangle22Widget3.dart';

/* Frame Admin manage kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdminmanagekategoriWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 831.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 224, 224),
                ),
              ),
              Positioned(
                left: 70.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 1140.0,
                height: 415.0,
                child: GeneratedRectangle21Widget4(),
              ),
              Positioned(
                left: 134.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 34.0,
                child: Generated1Widget6(),
              ),
              Positioned(
                left: 133.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 29.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 589.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 34.0,
                child: GeneratedMajalahWidget10(),
              ),
              Positioned(
                left: 133.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 34.0,
                child: Generated3Widget6(),
              ),
              Positioned(
                left: 71.0,
                top: 681.0,
                right: null,
                bottom: null,
                width: 1140.0,
                height: 150.0,
                child: GeneratedRectangle42Widget3(),
              ),
              Positioned(
                left: 122.0,
                top: 738.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 38.0,
                child: GeneratedAltheaGrisheldaAltheaRajinWidget3(),
              ),
              Positioned(
                left: 70.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 1140.0,
                height: 70.0,
                child: GeneratedRectangle22Widget3(),
              ),
              Positioned(
                left: 70.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 1140.0,
                height: 40.0,
                child: GeneratedRectangle23Widget4(),
              ),
              Positioned(
                left: 945.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle34Widget1(),
              ),
              Positioned(
                left: 945.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle43Widget1(),
              ),
              Positioned(
                left: 945.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle45Widget3(),
              ),
              Positioned(
                left: 1047.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle35Widget1(),
              ),
              Positioned(
                left: 1047.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle44Widget2(),
              ),
              Positioned(
                left: 1047.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle46Widget3(),
              ),
              Positioned(
                left: 122.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 35.0,
                child: GeneratedNoWidget6(),
              ),
              Positioned(
                left: 583.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 35.0,
                child: GeneratedKategoriWidget5(),
              ),
              Positioned(
                left: 1017.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 32.0,
                child: GeneratedEditWidget8(),
              ),
              Positioned(
                left: 973.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 27.0,
                child: GeneratedEditWidget9(),
              ),
              Positioned(
                left: 973.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 27.0,
                child: GeneratedEditWidget10(),
              ),
              Positioned(
                left: 973.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 27.0,
                child: GeneratedEditWidget11(),
              ),
              Positioned(
                left: 1064.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 27.0,
                child: GeneratedHapusWidget8(),
              ),
              Positioned(
                left: 1064.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 27.0,
                child: GeneratedHapusWidget9(),
              ),
              Positioned(
                left: 1064.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 27.0,
                child: GeneratedHapusWidget10(),
              ),
              Positioned(
                left: 527.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 38.0,
                child: GeneratedEDITKATEGORIWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedRectangle10Widget11(),
              ),
              Positioned(
                left: 205.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 32.0,
                child: GeneratedEditKategoriWidget1(),
              ),
              Positioned(
                left: 556.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 32.0,
                child: GeneratedTambahkanKategoriWidget1(),
              ),
              Positioned(
                left: 1025.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 40.0,
                child: GeneratedRectangle18Widget3(),
              ),
              Positioned(
                left: 24.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 40.0,
                child: GeneratedGroup1Widget11(),
              ),
              Positioned(
                left: 1230.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: 93.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 35.0,
                child: GeneratedHomeWidget1(),
              ),
              Positioned(
                left: 401.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 32.0,
                child: GeneratedEditBukuWidget1(),
              ),
              Positioned(
                left: 846.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 32.0,
                child: GeneratedTambahkanBukuWidget1(),
              ),
              Positioned(
                left: 1099.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 35.0,
                child: GeneratedLogoutWidget1(),
              ),
              Positioned(
                left: 1046.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 23.0,
                child: GeneratedSearchWidget3(),
              ),
              Positioned(
                left: 601.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 34.0,
                child: GeneratedNovelWidget17(),
              ),
              Positioned(
                left: 598.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 34.0,
                child: GeneratedKomikWidget1(),
              )
            ]),
      ),
    ));
  }
}
