import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedTerbaruWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedGroup116Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedLine19Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle180Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle183Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedMajalahWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedBukuWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle181Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese1widget/generated/GeneratedRectangle12Widget.dart';

/* Frame iPhone SE - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 320.0,
              height: 850.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 95.0,
                      right: null,
                      bottom: null,
                      width: 35.0,
                      height: 15.0,
                      child: GeneratedTerbaruWidget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 122.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 150.0,
                      child: GeneratedRectangle10Widget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 312.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 150.0,
                      child: GeneratedRectangle12Widget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 502.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 150.0,
                      child: GeneratedRectangle14Widget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 691.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 160.0,
                      child: GeneratedRectangle16Widget(),
                    ),
                    Positioned(
                      left: 180.0,
                      top: 311.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 150.0,
                      child: GeneratedRectangle13Widget(),
                    ),
                    Positioned(
                      left: 181.0,
                      top: 501.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 150.0,
                      child: GeneratedRectangle15Widget(),
                    ),
                    Positioned(
                      left: 181.0,
                      top: 690.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 160.0,
                      child: GeneratedRectangle17Widget(),
                    ),
                    Positioned(
                      left: 180.0,
                      top: 122.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 150.0,
                      child: GeneratedRectangle11Widget(),
                    ),
                    Positioned(
                      left: 10.0,
                      top: 95.0,
                      right: null,
                      bottom: null,
                      width: 10.0,
                      height: 10.0,
                      child: GeneratedRectangle180Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 320.0,
                      height: 80.0,
                      child: GeneratedRectangle1Widget(),
                    ),
                    Positioned(
                      left: 10.0,
                      top: 53.0,
                      right: null,
                      bottom: null,
                      width: 20.0,
                      height: 20.0,
                      child: GeneratedRectangle181Widget(),
                    ),
                    Positioned(
                      left: 89.0,
                      top: 56.0,
                      right: null,
                      bottom: null,
                      width: 65.0,
                      height: 20.0,
                      child: GeneratedMajalahWidget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 50.0,
                      right: null,
                      bottom: null,
                      width: 320.0,
                      height: 1.0,
                      child: GeneratedLine19Widget(),
                    ),
                    Positioned(
                      left: 192.0,
                      top: 55.0,
                      right: null,
                      bottom: null,
                      width: 66.0,
                      height: 18.0,
                      child: GeneratedRectangle183Widget(),
                    ),
                    Positioned(
                      left: 211.0,
                      top: 56.0,
                      right: null,
                      bottom: null,
                      width: 42.0,
                      height: 20.0,
                      child: GeneratedBukuWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 285.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedGroup1Widget(),
            ),
            Positioned(
              left: 96.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 138.0,
              height: 34.0,
              child: GeneratedGroup116Widget(),
            )
          ]),
    ));
  }
}
