import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedKaryaIlmiahWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedBukuWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedMajalahDewasaWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedNovelWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedMajalahWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedKomikWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine19Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedMajalahAnakWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedGroup116Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedSemuaKategoriWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle181Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedKategoriWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle180Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine21Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedMajalahWidget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedTerbaruWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedBukuWidget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese17widget/generated/GeneratedRectangle21Widget.dart';

/* Frame iPhone SE - 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIPhoneSE1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 320.0,
          height: 568.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 25.0,
                  top: 95.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 15.0,
                  child: GeneratedTerbaruWidget1(),
                ),
                Positioned(
                  left: 32.0,
                  top: 122.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 150.0,
                  child: GeneratedRectangle10Widget1(),
                ),
                Positioned(
                  left: 32.0,
                  top: 312.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 150.0,
                  child: GeneratedRectangle12Widget1(),
                ),
                Positioned(
                  left: 32.0,
                  top: 502.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 150.0,
                  child: GeneratedRectangle14Widget1(),
                ),
                Positioned(
                  left: 32.0,
                  top: 691.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 160.0,
                  child: GeneratedRectangle16Widget1(),
                ),
                Positioned(
                  left: 180.0,
                  top: 311.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 150.0,
                  child: GeneratedRectangle13Widget1(),
                ),
                Positioned(
                  left: 181.0,
                  top: 501.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 150.0,
                  child: GeneratedRectangle15Widget1(),
                ),
                Positioned(
                  left: 181.0,
                  top: 690.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 160.0,
                  child: GeneratedRectangle17Widget1(),
                ),
                Positioned(
                  left: 180.0,
                  top: 122.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 150.0,
                  child: GeneratedRectangle11Widget1(),
                ),
                Positioned(
                  left: 10.0,
                  top: 95.0,
                  right: null,
                  bottom: null,
                  width: 10.0,
                  height: 10.0,
                  child: GeneratedRectangle180Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 320.0,
                  height: 80.0,
                  child: GeneratedRectangle1Widget1(),
                ),
                Positioned(
                  left: 10.0,
                  top: 53.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 20.0,
                  child: GeneratedRectangle181Widget1(),
                ),
                Positioned(
                  left: 89.0,
                  top: 56.0,
                  right: null,
                  bottom: null,
                  width: 65.0,
                  height: 20.0,
                  child: GeneratedMajalahWidget1(),
                ),
                Positioned(
                  left: 203.0,
                  top: 56.0,
                  right: null,
                  bottom: null,
                  width: 43.0,
                  height: 20.0,
                  child: GeneratedBukuWidget1(),
                ),
                Positioned(
                  left: 285.0,
                  top: 56.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 15.0,
                  child: GeneratedGroup1Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 47.0,
                  right: null,
                  bottom: null,
                  width: 320.0,
                  height: 1.0,
                  child: GeneratedLine19Widget1(),
                ),
                Positioned(
                  left: 96.0,
                  top: 6.0,
                  right: null,
                  bottom: null,
                  width: 138.0,
                  height: 34.0,
                  child: GeneratedGroup116Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 568.0,
                  child: GeneratedRectangle21Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 31.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine9Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 62.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine10Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 92.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine13Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 122.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine14Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 152.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine15Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 182.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine16Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 212.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine17Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 242.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine18Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 272.0,
                  right: null,
                  bottom: null,
                  width: 200.0,
                  height: 1.0,
                  child: GeneratedLine21Widget(),
                ),
                Positioned(
                  left: 5.0,
                  top: 12.0,
                  right: null,
                  bottom: null,
                  width: 42.0,
                  height: 16.0,
                  child: GeneratedKategoriWidget(),
                ),
                Positioned(
                  left: 10.0,
                  top: 38.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 15.0,
                  child: GeneratedRectangle23Widget(),
                ),
                Positioned(
                  left: 33.0,
                  top: 39.0,
                  right: null,
                  bottom: null,
                  width: 72.0,
                  height: 13.0,
                  child: GeneratedSemuaKategoriWidget(),
                ),
                Positioned(
                  left: 27.0,
                  top: 71.0,
                  right: null,
                  bottom: null,
                  width: 27.0,
                  height: 16.0,
                  child: GeneratedBukuWidget2(),
                ),
                Positioned(
                  left: 27.0,
                  top: 190.0,
                  right: null,
                  bottom: null,
                  width: 39.0,
                  height: 16.0,
                  child: GeneratedMajalahWidget2(),
                ),
                Positioned(
                  left: 33.0,
                  top: 101.0,
                  right: null,
                  bottom: null,
                  width: 30.0,
                  height: 16.0,
                  child: GeneratedNovelWidget(),
                ),
                Positioned(
                  left: 33.0,
                  top: 222.0,
                  right: null,
                  bottom: null,
                  width: 60.0,
                  height: 13.0,
                  child: GeneratedMajalahAnakWidget(),
                ),
                Positioned(
                  left: 33.0,
                  top: 131.0,
                  right: null,
                  bottom: null,
                  width: 32.0,
                  height: 16.0,
                  child: GeneratedKomikWidget(),
                ),
                Positioned(
                  left: 33.0,
                  top: 252.0,
                  right: null,
                  bottom: null,
                  width: 72.0,
                  height: 13.0,
                  child: GeneratedMajalahDewasaWidget(),
                ),
                Positioned(
                  left: 33.0,
                  top: 160.0,
                  right: null,
                  bottom: null,
                  width: 55.0,
                  height: 24.0,
                  child: GeneratedKaryaIlmiahWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
