import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedTerbaruWidget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle11Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle12Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle14Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle15Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedGroup1Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedMajalahWidget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle16Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle17Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle13Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedRectangle10Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese4widget/generated/GeneratedBukuWidget5.dart';

/* Frame iPhone SE - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 706.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 35.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 24.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 132.1968231201172,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 132.1968231201172,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 20.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 166.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 20.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 86.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 20.0,
                child: GeneratedMajalahWidget5(),
              ),
              Positioned(
                left: 198.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 20.0,
                child: GeneratedBukuWidget5(),
              ),
              Positioned(
                left: 10.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 12.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 15.0,
                child: GeneratedTerbaruWidget4(),
              ),
              Positioned(
                left: 38.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle10Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle12Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle14Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle16Widget4(),
              ),
              Positioned(
                left: 196.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle11Widget4(),
              ),
              Positioned(
                left: 196.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle13Widget4(),
              ),
              Positioned(
                left: 196.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle15Widget4(),
              ),
              Positioned(
                left: 196.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 140.0,
                child: GeneratedRectangle17Widget4(),
              ),
              Positioned(
                left: 280.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup1Widget4(),
              )
            ]),
      ),
    ));
  }
}
