import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedRectangle183Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedKode101Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedRectangle189Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedRectangle185Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedRectangle187Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedDeskripsiWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedPenulisJsKhairenWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedStok3Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedMelangkahWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedListrikpadamdiseluruhJawadanBalisecaramisteriusAncamann.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese9widget/generated/GeneratedGroup117Widget.dart';

/* Frame iPhone SE - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 568.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle183Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle185Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 400.0,
                child: GeneratedRectangle187Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 130.0,
                child: GeneratedGroup117Widget(),
              ),
              Positioned(
                left: 87.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 198.0,
                child: GeneratedRectangle189Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 123.0,
                child:
                    GeneratedListrikpadamdiseluruhJawadanBalisecaramisteriusAncamann(),
              ),
              Positioned(
                left: 93.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 14.0,
                child: GeneratedKode101Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 14.0,
                child: GeneratedPenulisJsKhairenWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 17.0,
                child: GeneratedDeskripsiWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 14.0,
                child: GeneratedStok3Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 22.0,
                child: GeneratedMelangkahWidget(),
              )
            ]),
      ),
    ));
  }
}
