import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle17Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle10Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle16Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle180Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle11Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle12Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedMajalahWidget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle181Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedLine19Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedBukuWidget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedGroup1Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedTerbaruWidget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle13Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle15Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle14Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedRectangle182Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese7widget/generated/GeneratedGroup116Widget3.dart';

/* Frame iPhone SE - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 973.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 320.0,
                            height: 973.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 95.0,
                                    right: null,
                                    bottom: null,
                                    width: 35.0,
                                    height: 15.0,
                                    child: GeneratedTerbaruWidget3(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 122.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 150.0,
                                    child: GeneratedRectangle10Widget3(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 312.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 150.0,
                                    child: GeneratedRectangle12Widget3(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 502.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 150.0,
                                    child: GeneratedRectangle14Widget3(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 691.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 160.0,
                                    child: GeneratedRectangle16Widget3(),
                                  ),
                                  Positioned(
                                    left: 180.0,
                                    top: 311.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 150.0,
                                    child: GeneratedRectangle13Widget3(),
                                  ),
                                  Positioned(
                                    left: 181.0,
                                    top: 501.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 150.0,
                                    child: GeneratedRectangle15Widget3(),
                                  ),
                                  Positioned(
                                    left: 181.0,
                                    top: 690.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 160.0,
                                    child: GeneratedRectangle17Widget3(),
                                  ),
                                  Positioned(
                                    left: 180.0,
                                    top: 122.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 150.0,
                                    child: GeneratedRectangle11Widget3(),
                                  ),
                                  Positioned(
                                    left: 10.0,
                                    top: 95.0,
                                    right: null,
                                    bottom: null,
                                    width: 10.0,
                                    height: 10.0,
                                    child: GeneratedRectangle180Widget3(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 320.0,
                                    height: 80.0,
                                    child: GeneratedRectangle1Widget3(),
                                  ),
                                  Positioned(
                                    left: 10.0,
                                    top: 53.0,
                                    right: null,
                                    bottom: null,
                                    width: 20.0,
                                    height: 20.0,
                                    child: GeneratedRectangle181Widget3(),
                                  ),
                                  Positioned(
                                    left: 185.0,
                                    top: 55.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 18.0,
                                    child: GeneratedRectangle182Widget1(),
                                  ),
                                  Positioned(
                                    left: 89.0,
                                    top: 56.0,
                                    right: null,
                                    bottom: null,
                                    width: 65.0,
                                    height: 20.0,
                                    child: GeneratedMajalahWidget4(),
                                  ),
                                  Positioned(
                                    left: 203.0,
                                    top: 56.0,
                                    right: null,
                                    bottom: null,
                                    width: 43.0,
                                    height: 20.0,
                                    child: GeneratedBukuWidget4(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 47.0,
                                    right: null,
                                    bottom: null,
                                    width: 320.0,
                                    height: 1.0,
                                    child: GeneratedLine19Widget3(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 285.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedGroup1Widget3(),
            ),
            Positioned(
              left: 96.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 138.0,
              height: 34.0,
              child: GeneratedGroup116Widget3(),
            )
          ]),
    ));
  }
}
