import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedRectangle9Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedLihatPasswordWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedLine1Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedLine2Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedRectangle1Widget8.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedLOGINADMINWidget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/bookspaceapp/generatedadminloginwidget/generated/GeneratedPasswordWidget.dart';

/* Frame Admin Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdminLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 390.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 490.0,
                height: 410.0,
                child: GeneratedRectangle1Widget8(),
              ),
              Positioned(
                left: 430.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 1.0,
                child: GeneratedLine1Widget4(),
              ),
              Positioned(
                left: 430.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 1.0,
                child: GeneratedLine2Widget4(),
              ),
              Positioned(
                left: 585.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 40.0,
                child: GeneratedRectangle9Widget4(),
              ),
              Positioned(
                left: 575.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 26.0,
                child: GeneratedLOGINADMINWidget(),
              ),
              Positioned(
                left: 501.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 23.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 501.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 23.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 501.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 17.0,
                child: GeneratedLihatPasswordWidget(),
              ),
              Positioned(
                left: 611.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 23.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 450.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 22.000001907348633,
                height: 22.000001907348633,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 450.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 22.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 453.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 15.000000953674316,
                height: 15.0,
                child: GeneratedGroup8Widget(),
              )
            ]),
      ),
    ));
  }
}
