import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedRectangle185Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedRectangle187Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedMajalahanakWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedKode101Widget3.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedSaranaBoboGroupofMagazineWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedBoboWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedRectangle183Widget5.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedRectangle189Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedGroup117Widget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedDeskripsiWidget4.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese16widget/generated/GeneratedStok3Widget4.dart';

/* Frame iPhone SE - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 568.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle183Widget5(),
              ),
              Positioned(
                left: 12.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle185Widget4(),
              ),
              Positioned(
                left: 35.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 400.0,
                child: GeneratedRectangle187Widget4(),
              ),
              Positioned(
                left: 115.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 130.0,
                child: GeneratedGroup117Widget4(),
              ),
              Positioned(
                left: 87.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 198.0,
                child: GeneratedRectangle189Widget4(),
              ),
              Positioned(
                left: 92.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 13.0,
                child: GeneratedMajalahanakWidget1(),
              ),
              Positioned(
                left: 93.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 14.0,
                child: GeneratedKode101Widget3(),
              ),
              Positioned(
                left: 82.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 14.0,
                child: GeneratedSaranaBoboGroupofMagazineWidget1(),
              ),
              Positioned(
                left: 92.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 17.0,
                child: GeneratedDeskripsiWidget4(),
              ),
              Positioned(
                left: 93.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 14.0,
                child: GeneratedStok3Widget4(),
              ),
              Positioned(
                left: 143.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 22.0,
                child: GeneratedBoboWidget1(),
              )
            ]),
      ),
    ));
  }
}
