import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedRectangle185Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedGroup117Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedDeskripsiWidget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedRectangle187Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedKode301Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedRectangle183Widget2.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedRectangle189Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedPenulisOnoEricoWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedStok3Widget1.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedMiikoWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese11widget/generated/GeneratedHarihariMiikodankawankawandiSDSuginokitelahusaiSambilme.dart';

/* Frame iPhone SE - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 568.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle183Widget2(),
              ),
              Positioned(
                left: 12.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle185Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 400.0,
                child: GeneratedRectangle187Widget1(),
              ),
              Positioned(
                left: 115.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 130.0,
                child: GeneratedGroup117Widget1(),
              ),
              Positioned(
                left: 87.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 198.0,
                child: GeneratedRectangle189Widget1(),
              ),
              Positioned(
                left: 92.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 112.0,
                child:
                    GeneratedHarihariMiikodankawankawandiSDSuginokitelahusaiSambilme(),
              ),
              Positioned(
                left: 93.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 14.0,
                child: GeneratedKode301Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 14.0,
                child: GeneratedPenulisOnoEricoWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 17.0,
                child: GeneratedDeskripsiWidget1(),
              ),
              Positioned(
                left: 93.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 14.0,
                child: GeneratedStok3Widget1(),
              ),
              Positioned(
                left: 141.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 22.0,
                child: GeneratedMiikoWidget(),
              )
            ]),
      ),
    ));
  }
}
