import 'package:flutter/material.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedRectangle191Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedRectangle187Widget8.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedJudulBukuWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedRectangle188Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedRectangle183Widget9.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedLine24Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedGroup117Widget8.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedPenulisWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedRectangle185Widget8.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedDeskripsiWidget8.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedRectangle186Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedStokWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedRectangle189Widget8.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedLine25Widget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedKodeWidget.dart';
import 'package:flutterapp/bookspaceapp/generatediphonese10widget1/generated/GeneratedRectangle190Widget.dart';

/* Frame iPhone SE - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneSE10Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 320.0,
        height: 568.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle183Widget9(),
              ),
              Positioned(
                left: 12.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle185Widget8(),
              ),
              Positioned(
                left: 12.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine24Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 28.284271240234375,
                height: 1.0,
                child: GeneratedLine25Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 20.0,
                child: GeneratedRectangle186Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 400.0,
                child: GeneratedRectangle187Widget8(),
              ),
              Positioned(
                left: 115.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 130.0,
                child: GeneratedGroup117Widget8(),
              ),
              Positioned(
                left: 89.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 15.0,
                child: GeneratedRectangle188Widget(),
              ),
              Positioned(
                left: 87.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 15.0,
                child: GeneratedRectangle189Widget8(),
              ),
              Positioned(
                left: 87.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 15.0,
                child: GeneratedRectangle190Widget(),
              ),
              Positioned(
                left: 87.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 15.0,
                child: GeneratedRectangle191Widget(),
              ),
              Positioned(
                left: 93.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 17.0,
                child: GeneratedKodeWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 17.0,
                child: GeneratedPenulisWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 17.0,
                child: GeneratedDeskripsiWidget8(),
              ),
              Positioned(
                left: 93.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 17.0,
                child: GeneratedStokWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 19.0,
                child: GeneratedJudulBukuWidget(),
              )
            ]),
      ),
    ));
  }
}
